// import { Injectable } from '@angular/core';
//
// @Injectable()

// tslint:disable-next-line:new-parens
export default new class Language {

  EN: any = {
    password_changed: 'Password changed',
    user_not_found: 'Expired key or user not found',
    check_forgot_password: 'Please check your email inbox or spam folder. ',
    REG_FUNDAMENTALS: 'Register for javascript fundamentals',
    REG_APP: 'Register for learning web applications',
    knowledge: "Knowledge",
    VIEW: 'View',
    DOWNLOAD: 'Download',
    abt: {
      soft_title: "Creating software products",
      soft_desc: "We are getting involved into product requirements, good communication with the clients, software delivery",
      soft_req: "Request software",
      soft_req_desc: "After you will post the project details, we will contact you for a better software analysis",
      proto: "Prototyping",
      proto_desc: "Having this prototype is essential in the process of software delivery",
      impl: "Implementation",
      impl_desc: "We will establish sequencial steps of delivery of the application ",
      course_desc: "Training people which want to learn the development process",
    },
    home: {
      title: "Courses & IT projects",
      proj: 'Do you need a project?',
      proj_desc: "Would you like to check what we can help?",
      dev: "Developer skills",
      dev_desc: 'Add your development skills',
      course: "Subscribe for courses ",
      course_desc: "6 months, 2 phases, approximately 900 euro ",
    },
    proj: {
      name: 'Project name',
      about: 'Tell us more about your project',
      skills: 'What skills are required?',
      pay: 'How do you want to pay?',
      budget: 'What is your estimated budget?',
      empty_proj: 'No project were added',
      
    },
    COURSE_LINKS: {
      DESC: 'About',
      WHO: 'Audience',
      PROGRAMA: 'Curricullum',
      REGISTER: 'Register',
      SESSION1: 'Session I (fundamentals)',
      SESSION2: 'Session II (application, server, OOP)',
      test: 'Test',
      app: 'Application',
      server: 'Server',
      sesion1: 'Meeting 1',
      part2: 'Fundaments',
      diploma: 'Certificate',
    },
    confirmation_code: "Email already confirmed",
    registered: 'You have succesfully registered',
    HELLO: 'Hello', 
    COURSES: 'Courses',
    PROJ_DETAIL: 'Project Details',
    My_PROJECTS: 'My Projects',
    PAY_FIX: 'Fix Price',
    PAY_HOUR: 'Pay by the hour',
    CODE: 'Code',
    SOLUTIONS: 'Solutions',
    MESSAGES: 'Messages',
    TEST_CASES: 'Test Cases',
    VIEWER: 'View',
    MENU_HOME: 'Home',
    MENU_DISCUSSIONS: 'Discussions',
    MENU_SEARCH: 'Search',
    MENU_SERVICES: 'Services',
    MENU_QUESTIONS: 'Questions',
    MENU_QUIZ: 'Quiz',
    MENU_PAYMENT: 'Payment',
    MENU_LOGIN: 'Login',
    MENU_SETTINGS: 'Settings',
    MENU_LOGOUT: 'Logout',
    MENU_PERSONAL_DATA: 'Personal Data',
    MENU_ABOUT: 'About',
    MENU_LANGUAGE: 'Language',
    MENU_EN: 'EN',
    MENU_RO: 'RO',
    NICK: 'Nick',
    LOGIN: 'Login',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CANCEL: 'Cancel',
    NEW_USER: 'New User',
    RESET_PASSWORD: 'Reset Password',
    FACEBOOK_LOGIN: 'Login with Facebook',
    EMPTY_PASSWORD: 'Empty Password',
    EMPTY_EMAIL: 'EMpty Email',
    CHANNELS: 'Channels',
    CHAT: 'Chat',
    TOPIC_ADD: 'Add Topic',
    TOPIC_EDIT: 'Edit Topic',
    ALL: 'All',
    MY: 'My',
    WRITE_MESSAGE: 'write message',
    CATEGORY_SELECT: 'Select Category',
    CATEGORY_ADD: 'Add new category',
    MAP: 'Map',
    USE_MAP: 'Use Map',
    POINTS: 'Points',
    QUESTION_ADD: 'Add question',
    QUESTION_EDIT: 'Edit question',
    ROOMS: 'Rooms',
    QUESTIONS: 'Questions',
    DETAILS: 'Details',
    EDIT_USER: 'Edit User',
    NAME: 'Name',
    SURNAME: 'Last Name ',
    PHONE: 'Phone',
    SAVE: 'Save',
    DELETE: 'Delete',
    LOCATION: 'Location',
    IMAGES: 'Images',
    USER_LOCATION: 'User Location',
    SEARCH: 'Search',
    CATEGORY: 'Category',
    MY_MESSAGES: 'My Messages',
    PUBLIC_MESSAGES: 'Public Messages',
    NEW_CATEG: 'Add new category ...',
    PARENT: 'Parent',
    EDIT: 'Edit',
    CONTENT: 'Content',
    ROOM_NEW: 'New Room',
    ROOM_JOIN: 'Join Room',
    ROOM_LEAVE: 'Leave Room',
    READY: 'Ready',
    CURRENT_QUESTION: 'Current question(s)',
    ANSWERS: 'Answers',
    SEND: 'Send',
    QUESTION_NO: 'Question no:',
    NEXT: 'Next',
    PAYMENT: 'Payment',
    PAYMENT_HIST: 'Payment History',
    CARD_PAY: 'Card Payment',
    CARD_NUMBER: 'Card Number',
    CARD_HOLDER_NAME: 'Cardholder Name',
    CARD_EXPIRE: 'Expiration Date',
    CARD_CVV: 'CVV',
    CARD_AMOUNT: 'Amount',
    CARD_AMOUNT_OLD: 'Old Amount',
    CARD_AMOUNT_NEW: 'New Amount',
    DATE: 'Date',
    STATUS: 'Status',
    SERVICE_MY: 'My Services',
    SERVICE_NEW: 'New Service name',
    SERVICE_CREATE: 'Create New Service',
    IS_ACTIVE: 'Is Active',
    TITLE: 'Title',
    WEB_SITE: 'Web Site',
    DESCRIPTION: 'Description',
    ADDED: 'Added',
    UPDATED: 'Updated',
    USER_MESSAGES: 'User Messages',
    SEARCH_WORDS: 'Words from title it will be used for search',
    DELETE_CONF_SERVICE: 'Are you sure you want to delete {0} service?',
    PREV: 'Previous',
    S_TEMP: 'Temporary',
    S_SEZ: 'Seasonal',
    S_LONG: 'Long Term',
    T_M: '1 month',
    T_S: '3 months',
    T_Y: '1 year',
    S_REGISTER: 'Register',
    S_BUY: 'Buy coins',
    F_SEND: 'Send',
    ADD_SERVICE: 'Add Service',
    EXPENSES: 'Expences',
    REQUEST: 'Request',
    OFFER: 'Offer',
    S_TYPE: 'Service type',
    S_DURATION: 'Service period',
    COINS: 'Coins',
    TOTAL_VALUE : 'Total Value',
    CURRENCY: 'Currency',
    Q_ENUNT: 'Content',
    CORRECT_ANS: 'Select the correct answer',
    PGN_GAME: 'Load PGN ',
    FEN_POSITION: 'FEN Position',
    CHESS_POSITION: 'Set initial position',
    CHESS_OPENINGS: 'Openings',
    CHESS_GAMES: 'Chess Games',
    CHESS_MY_GAMES: 'My Games',
    ONLINE_USERS: 'Online users',
    SCHOOL_LIST: 'School List',
    FIND_BEST_MOVE: 'Find the best move',
    SETTINGS: 'Settings',
    CHESS: 'Chees',
    GAME_HISTORY: 'Game History',
    GAME_INVITATIONS: 'Invitations',
    DRAW_PROPOSAL: 'Draw proposed by {0}. Do you accept?',
    email_used: 'Email is already used',
    other_player: 'Other Player',
    computer: 'Calculator',
    engine_logs: 'Engine Logs',
    no_time: '0',
    PLAY_CHESS: 'Play Chess',
    SEND_FEEDBACK: 'If you have any suggestions please send us a message',
    ADD_SCHOOL: 'Add School',
    EDIT_SCHOOL: 'Edit School',
    ADD_QUESTION: 'Add Question',
    EDIT_QUESTION: 'Edit Question',
  };

  RO: any = {
    password_changed: 'Parola a fost schimbata',
    user_not_found: 'Cheie expirata sau utilizatorul nu a fost gasit',
    check_forgot_password: 'Un email a fost trimis pentru resetarea parolei. Verifica si directorul spam.',
    REG_FUNDAMENTALS: 'Inregistrare sesiune 1: javascript fundamentals',
    REG_APP: 'Inregistrare sesiune 2: creare aplicatie web',
    knowledge: "Cunostinte",
    VIEW: 'Vizualizare',
    DOWNLOAD: 'Descarca',
    abt: {
      soft_title: "Realizarea proiectelor soft",
      soft_desc: "Ne implicam in analiza cerintelor, comunicare activa cu clientii, creare prototipuri, livrare si mentenanta",
      soft_req: "Cerere realizare proiect",
      soft_req_desc: "Dupa trimiterea cerintelor proiectului, veti fi contactati pentru o analiza mai amanuntita a cerintelor",
      proto: "Creare prototip",
      proto_desc: "Crearea acestui protopit al aplicatiei este esential in procesul de livrare a produsului",
      impl: "Implementare si mentenanta",
      impl_desc: "Implementarea softului sa va face in pasi stabiliti de comun acord",
      course_desc: "Pregatire cursanti in vederea acumularii cunostintelor de programare",
    },
    home: {
      title: "Cursuri si proiecte IT",
      proj: 'Doriti realizarea unui proiect? ',
      proj_desc: "Haideti sa vedem proiectele / tehnologiile care ne-ar ajuta la proiect",
      dev: "Colaboreaza cu noi",
      dev_desc: 'Adauga tehnologiile stapanite',
      course: "Inscriere cursuri ",
      course_desc: " 6 luni, 2 etape, aproximativ 4000 ron ",
    },
    proj: {
      name: 'Nume proiect',
      about: 'Cateva cuvinte despre proiect',
      skills: 'Care sunt abilitatile necesare realizarii proiectului?',
      pay: 'Care este metoda de plata?',
      budget: 'Care este bugetul estimat?',
      empty_proj: 'Nu ati adaugat nici un proiect (deocamdata) ',
    },
    COURSE_LINKS: {
      DESC: 'Despre',
      WHO: 'Cui ne adresam',
      PROGRAMA: 'Programa',
      REGISTER: 'Inregistrare',
      SESSION1: 'Sessiune I (fundamente programare)',
      SESSION2: 'Sessiune II (aplicatie, server, OOP)',
      test: 'Test',
      app: 'Aplicatie',
      server: 'Server',
      sesion1: 'Sedinta 1',
      part2: 'Fundamente',
      diploma: 'Diploma'
    },
    confirmation_code: "Emailul este confirmat",
    registered: 'V-ati inregistrat cu succes',
    HELLO: 'Buna',
    COURSES: 'Cursuri',
    PROJ_DETAIL: 'Detalii proiect',
    My_PROJECTS: 'Proiectele mele',
    PAY_FIX: 'Pret fix',
    PAY_HOUR: 'Pret pe ora',
    CODE: 'Rezolvarea mea',
    SOLUTIONS: 'Solutii',
    MESSAGES: 'Mesaje',
    TEST_CASES: 'Testare',
    VIEWER: 'Vizualizare', 
    MENU_HOME: 'Acasa',
    MENU_DISCUSSIONS: 'Discutii',
    MENU_SEARCH: 'Cautare',
    MENU_SERVICES: 'Servicii',
    MENU_QUESTIONS: 'Intrebari',
    MENU_QUIZ: 'Quiz',
    MENU_PAYMENT: 'Plata',
    MENU_LOGIN: 'Logare',
    MENU_SETTINGS: 'Setari',
    MENU_LOGOUT: 'Deconectare',
    MENU_PERSONAL_DATA: 'Date Personale',
    MENU_ABOUT: 'Despre',
    MENU_LANGUAGE: 'Limba',
    MENU_EN: 'EN',
    MENU_RO: 'RO',
    NICK: 'Pseudonim',
    LOGIN: 'Logare',
    EMAIL: 'Email',
    PASSWORD: 'Parola',
    CANCEL: 'Renunta',
    NEW_USER: 'Utilizator Nou',
    RESET_PASSWORD: 'Resetare Parola',
    FACEBOOK_LOGIN: 'Logare cu Facebook',
    EMPTY_PASSWORD: 'Parola invalida',
    EMPTY_EMAIL: 'Email invalid',
    CHANNELS: 'Canale',
    CHAT: 'Chat',
    TOPIC_ADD: 'Adaugare director',
    TOPIC_EDIT: 'Editare director',
    ALL: 'Toate',
    MY: 'A mele',
    WRITE_MESSAGE: 'scrie mesaj',
    CATEGORY_SELECT: 'Selecteaza categoria',
    CATEGORY_ADD: 'Adauga caegorie noua',
    MAP: 'Harta',
    USE_MAP: 'Foloseste harta',
    POINTS: 'Puncte',
    QUESTION_ADD: 'Adaugare intrebare',
    QUESTION_EDIT: 'Editare intrebare',
    ROOMS: 'Camere',
    QUESTIONS: 'Intrebari',
    DETAILS: 'Detalii',
    EDIT_USER: 'Editeaza utilizatorul',
    NAME: 'Nume',
    SURNAME: 'Prenume',
    PHONE: 'Telefon',
    SAVE: 'Salveaza',
    DELETE: 'Sterge',
    LOCATION: 'Locatie',
    IMAGES: 'Imagini',
    USER_LOCATION: 'Locatia curenta',
    SEARCH: 'Cautare',
    CATEGORY: 'Categorie',
    MY_MESSAGES: 'Mesaje proprii',
    PUBLIC_MESSAGES: 'Mesaje publice',
    NEW_CATEG: 'Adaugare categorie ...',
    PARENT: 'Parinte',
    EDIT: 'Editare',
    CONTENT: 'Continut',
    ROOM_NEW: 'Camera noua',
    ROOM_JOIN: 'Intrare Camera',
    ROOM_LEAVE: 'Parasire Camera',
    READY: 'Sa incepem',
    CURRENT_QUESTION: 'Intrebarile actuale',
    ANSWERS: 'Raspunsuri',
    SEND: 'Trimite',
    QUESTION_NO: 'Enuntul nr',
    NEXT: 'Inainteaza',
    PAYMENT: 'Plata',
    PAYMENT_HIST: 'Istoric Plati',
    CARD_PAY: 'Plata Card',
    CARD_NUMBER: 'Numar Card',
    CARD_HOLDER_NAME: 'Nume Detinator',
    CARD_EXPIRE: 'Data expirare',
    CARD_CVV: 'CVV',
    CARD_AMOUNT: 'Suma',
    CARD_AMOUNT_OLD: 'Suma veche',
    CARD_AMOUNT_NEW: 'Noua suma',
    DATE: 'Data',
    STATUS: 'Status',
    SERVICE_MY: 'Serviciile mele',
    SERVICE_NEW: 'Numele noului serviciu',
    SERVICE_CREATE: 'Creaza serviciu nou',
    IS_ACTIVE: 'Serviciul este activ',
    TITLE: 'Titlu',
    WEB_SITE: 'Site Web',
    DESCRIPTION: 'Descriere',
    ADDED: 'Adaugat',
    UPDATED: 'Modificat',
    USER_MESSAGES: 'Mesaje utilizatori',
    SEARCH_WORDS: 'Cuvintele din tilu vor fi folosite la cautare din meniul de Cautare',
    DELETE_CONF_SERVICE: 'Sunteti sigur ca doriti sa stergeti serviciul {0} ?',
    PREV: 'Anterior',
    S_TEMP: 'Temporar',
    S_SEZ: 'Sezonier',
    S_LONG: 'Termen lung',
    T_M: '1 luna',
    T_S: '3 luni',
    T_Y: '1 an',
    S_REGISTER: 'Inregistrare',
    S_BUY: 'Cumparare monezi',
    S_TYPE: 'Tipul serviciului',
    S_DURATION: 'Durata serviciului',
    F_SEND: 'Trimite',
    ADD_SERVICE: 'Adaugare serviciu',
    EXPENSES: 'Cheltuieli',
    REQUEST: 'Cerere',
    OFFER: 'Oferta',
    COINS: 'Monezi',
    TOTAL_VALUE : 'Valoare Totala',
    CURRENCY: 'Moneda',
    Q_ENUNT: 'Enunt',
    CORRECT_ANS: 'Bifati raspunsul corect',
    PGN_GAME: 'Incarcare PGN ',
    FEN_POSITION: 'Incarcare pozitie FEN',
    CHESS_POSITION: 'Setare pozitie intiala',
    CHESS_OPENINGS: 'Deschideri',
    CHESS_GAMES: 'Jocuri celebre',
    CHESS_MY_GAMES: 'Jocurile mele',
    ONLINE_USERS: 'Utilizatori activi',
    SCHOOL_LIST: 'Lista scoli',
    FIND_BEST_MOVE: 'Cea mai buna mutare',
    SETTINGS: 'Setari',
    CHESS: 'Sah',
    GAME_HISTORY: 'Istoric Mutari',
    GAME_INVITATIONS: 'Invitatii Joc',
    DRAW_PROPOSAL: '{0} a propus remiza. Accepti?',
    email_used: 'Emailul este folosit',
    other_player: 'Alt Jucator',
    computer: 'Calculator',
    engine_logs: 'Loguri Stockfish',
    no_time: '0',
    PLAY_CHESS: 'Joaca sah',
    SEND_FEEDBACK: 'Trimiteti un mesaj',
    ADD_SCHOOL: 'Adaugare scoala',
    EDIT_SCHOOL: 'Modificare scoala',
    ADD_QUESTION: 'Adaugare',
    EDIT_QUESTION: 'Modificare',
  };

};
